spring.application.name=api-gateway
server.port=8090
#Rutas del microservicio de productos
spring.cloud.gateway.server.webflux.routes[0].id=ms-catalogos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-catalogos
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/catalogos/**

#Rutas del microservicio de inventario
spring.cloud.gateway.server.webflux.routes[1].id=ms-cuentas
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-cuentas
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/cuentas/**

#Rutas del microservicio de ventas
# Pendiente de implementar!
spring.cloud.gateway.server.webflux.routes[2].id=ms-prestamos_mqm
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-prestamos_mqm
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/prestamos/**

#Rutas del microservicio de departamento
spring.cloud.gateway.server.webflux.routes[3].id=ms-tarjetas
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-tarjetas
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/tarjetas/**

#Rutas del microservicio de transacciones
spring.cloud.gateway.server.webflux.routes[4].id=ms-transacciones
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-transacciones
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/transacciones/**

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8095/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}